#!/usr/bin/env ruby
# vim: set expandtab ts=2 sw=2 nowrap ft=ruby ff=unix fenc=utf-8 :

require 'json'

top_level_path = `git rev-parse --show-toplevel`.chomp

err = false
begin
  JSON.parse(IO.read(File.join(top_level_path, 'kantan-ej-dictionary.json')))
rescue => e
  puts "Cannot parse kantan-ej-dictionary.json"
  err = true
end

exit err ? 1 : 0
